'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Dieser Quellcode wurde automatisch generiert von xsd, Version=4.7.3081.0.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True),
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)>
Partial Public Class ConfigSetting

    Private applicationPathField As String

    Private configPathLokalField As String

    Private configPathEntwicklungField As String

    Private configPathProduktionField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
    Public Property ApplicationPath() As String
        Get
            Return Me.applicationPathField
        End Get
        Set
            Me.applicationPathField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
    Public Property ConfigPathLokal() As String
        Get
            Return Me.configPathLokalField
        End Get
        Set
            Me.configPathLokalField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
    Public Property ConfigPathEntwicklung() As String
        Get
            Return Me.configPathEntwicklungField
        End Get
        Set
            Me.configPathEntwicklungField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
    Public Property ConfigPathProduktion() As String
        Get
            Return Me.configPathProduktionField
        End Get
        Set
            Me.configPathProduktionField = value
        End Set
    End Property
End Class
